export default {
  SignIn_Title: "Please log in using your username and password",
  password: "password",
  name: "username",
  Sign_In: "Log In",
  More: "More",
  Select: "Select",
  Seats: "Seats",
  Show: "Show",
  Free: "Free",
  Language: "Language",
  English: "English",
  Romania: "Romania",
  Release_day: "Open Up Day",
  Notification_sound_ON_OFF: "Notifications",
  Paid_Online: "Paid",
  Created_for: "Made for",
  Order_No: "Reservation no.",
  Position: "Seats",
  Days_of_reservation: "Reservation Days",
  No_result: "No results",
  Discount: "Discount",
  Partial_Release: "Partly Open Up",
  Release: "Release",
  Pay: "Pay",
  Mark_Occupied: "Mark On Location",
  Released_days: "Opened Up Days",
  Reject: "Reject",
  Request_Number: "Request Number",
  Cancel: "Cancel",
  Accept: "Accept",
  Check: "Check",
  Set_Position: "Set Position",
  Check_Customer: "Check Photo",
  Customer: "Customer",
  Reset: "Reset",
  Reservation_days: "Reservation Days",
  Release_detail: "Select the days you want to open up then press Open Up button",
  Pending: "Pending Confirmation",
  Unread: "Unread",
  Occupied: "On Location",
  Close: 'Close',
  Choose_an_area: "Choose a zone",
  area: "zone",
  choose_location: "choose location",
  Done: "Done",
  Selected_Seats: "Selected Seats",
  zone_alert: "Please reconsider your selection. You cannot select seats from different zones.",
  Success: "Success",
  Positions_set_successfully: "Selection set successfully",
  OK: "OK",
  Cancel: "Cancel",
  Set_Position: "Set Position",
  Change_Position: "Change Position",
  Open: "Next",
  Today: "Today",
  Tomorrow: "Tomorrow",
  Select: "Select",
  Seats: "Seats",
  Show: "Show",
  Free: "Free",
  Beach: "Beach",
  Pool: "Pool",
  Terrace: "Terrace",
  Restaurant: "Restaurant",
  Club: "Club",
  Add_Reservation: "Add a Reservation",
  Create_Reservation: "Make a Reservation",
  Are_you_sure: "Are you sure?",
  Yes: "Yes",
  No: "No",
  Release: "Rlease",
  Name: "Name",
  Phone: "Phone Number",
  Comment: "Booking Notes",
  Total_Price: "Total",
  Mark_booked: "Mark Booked",
  Mark_occupied: "Mark On Location",
  Protocol: "Protocol",
  Discount: "Discount",
  Select_discount_percentage: "Discount Type",
  By_percent: "Percentage",
  By_amount: "Amount",
  Average_price: "Price",
  Extra_sundebs: "Extra sunbeds",
  Release_days: "Open Calendar",
  Release_content: " Select the days you want to open up then press Open Up button",
  Select_All: "Select All",
  Update: "Update",
  Delete: "Delete",
  Extra_Sunbeds: "Extra Sunbeds",
  Rent_Umbrella: "Umbrellas",
  Status: "Status",
  reserve_not_paid: "Reserve(Not Paid)",
  reserved_paid: " Reserve (Paid)",
  Days_selected: "Selected Days",
  discount_alert: "Discount higher than Total Price",
  Created_by: "Made by",
  Go_in: "Go in",
  Reservation_Number: "Reservation Number",
  new_on_smart_beach: "New to Tabo?",
  already_have_account: "Already have an account?",
  SIGN_UP: "SIGN UP",
  LOG_IN: "LOG IN",
  Receptionist: "Receptionist",
  Search_location: "Search location",
  UserName: "Username",
  Code: "PIN Code",
  Verify: "Verify",
  New_password: "New Password",
  Confirm_password: "Confirm Password",
  username_password_incorrect: "Incorrect username or password",
  password_incorrect: " Incorrect username or password",
  //////////////////////////////
  Reservation_Data: "Reservation Data",
  Reservation_No: "Reservation No",
  Phone_No: "Phone No",
  Period: "Period",
  Price: "Price",
  Scan_again: "Scan again",
  Confirm_Arrival: "Confirm Arrival",
  Reservation_Not_found: "Reservation Not found. Try again.",
  Name_Phone_No: "Name & Phone No",
  Success_change_status: "Success change status",
  different_select_days: "Days Selected Diff.",
  Change_Status: "Change Status",
  Table_Number: "Table Number",
  Reservation_day: "Reservation Day",
  Arrive_time: "Arrival time",
  number_of_persons: "Number of persons",
  persons: "Persons",
  View: "View",
  Change: "Change",
  Completed: "Completed",
  Arrived: "Arrived",
  Remove: "Remove",
  ////////////////////////////////////////
  INFO: "INFO",
  ConfirmationAlert1: "You are not allow to create reservation if is before present time.",
  ConfirmationAlert2: "Reconsider your choise",
  Confirm_changings: "Confirm changings",
  from_start_hour: "- From start hour",
  to: "to",
  from_table: "- From table",
  to_table: "to table",
  time_occupied_from: "- Time occupied from",
  min: "min",
  change_status_canceled: "Change Status : Canceled",
  are_you_sure: "Are you sure?",
  ok: "OK",
  change_status_occupied: "Change Status : Occupied",
  change_status_completed: "Change Status : Completed",
  Phone_Number: "Phone Number",
  Number_of_persons: 'Number of Persons',
  Date: 'Date',
  Start_Time: "Start Time",
  Range: "Range",
  mins: "mins",
  mark_booked: "Mark Booked",
  mark_occupied: "Mark Occupied",
  Late: "Late",
  Failed_storage: "Failed to save the data to the storage",
  Success_update: "Success updated",
  Success_Release: "Success Release",
  Break_time: "Break time",
  Colitions: "Reservations colides, not allow",
  Name_must_be_exist: "Name must be exist.",
  Selected_Seats: "Selected Seats",
  Calendar: "Calendar",
  Select_Individual_Days: "Select Individual Days"
};