export default {
  SignIn_Title: "Logheaza-te folosind nume utilizator si parola",
  password: "parola",
  name: "nume utilizator",
  Sign_In: "Logheaza-te",
  More: "Mai mult",
  Select: "Selecteaza",
  Seats: "Locuri",
  Show: "Arata",
  Free: "Liber",
  Language: "Limba",
  English: "Engleza",
  Romania: "Romana",
  Release_day: "Elibereaza",
  Notification_sound_ON_OFF: "Notificari",
  Paid_Online: "Platit Online",
  Created_for: "Creat pentru",
  Order_No: "Nr. rezervare",
  Position: "Pozitie",
  Days_of_reservation: "Zile rezervate",
  No_result: "Nu exista rezultate",
  Discount: "Discount",
  Partial_Release: "Partial eliberat",
  Release: "Eliberat",
  Pay: "Plateste",
  Mark_Occupied: "Marcheaza Ocupat",
  Released_days: "Zile eliberate",
  Reject: "Respinge",
  Request_Number: "Numar solicitare",
  Cancel: "Anuleaza",
  Accept: "Accepta",
  Check: "Verifica",
  Set_Position: "Seteaza pozitie",
  Check_Customer: "Verifica Poza",
  Customer: "Client",
  Reset: "Reseteaza",
  Reservation_days: "Zile rezervate",
  Release_detail: "Detalii eliberare",
  Pending: "In asteptare",
  Unread: "Necitit",
  Occupied: "Ocupat",
  Close: 'Inchis',
  Choose_an_area: "Alege o zona",
  area: "zona",
  choose_location: "Alege locatia",
  Done: "Confirma",
  Selected_Seats: "Selecteaza locuri",
  zone_alert: "Recosidera alegerea facuta. Nu poti selecta locuri din zone diferite",
  Success: "Cu Succes",
  Positions_set_successfully: "Selectia facuta cu succes",
  OK: "OK",
  Cancel: "Anuleaza",
  Set_Position: "Seteaza pozitia",
  Change_Position: "Schimba Pozitia",
  Open: "Deschide",
  Today: "Azi",
  Tomorrow: "Maine",
  Select: "Alege",
  Seats: "Locuri",
  Show: "Arata",
  Free: "Liber",
  Beach: "Plaja",
  Pool: "Piscina",
  Terrace: "Terasa",
  Restaurant: "Restaurant",
  Club: "Club",
  Add_Reservation: "Adauga rezervare",
  Create_Reservation: "Creaza Rezervare",
  Are_you_sure: "Esti sigur?",
  Yes: "Da",
  No: "Nu",
  Release: "Elibereaza",
  Name: "Nume",
  Phone: "Telefon",
  Comment: "Comentariu",
  Total_Price: "Pret Total",
  Mark_booked: "Marcheaza Rezervat",
  Mark_occupied: "Marcheaza Ocupat",
  Protocol: "Protocol",
  Discount: "Discount",
  Select_discount_percentage: "Tip Discount",
  By_percent: "Procentual",
  By_amount: "Valoric",
  Average_price: "Pret estimat",
  Extra_sundebs: "Locuri extra",
  Release_days: "Deschide Calendar",
  Release_content: "Selecteaza zilele pe care vrei sa le deschizi si apasa Deschide Calendar",
  Select_All: "Selecteaza tot",
  Update: "Updateaza",
  Delete: "Sterge",
  Extra_Sunbeds: "Locuri extra",
  Rent_Umbrella: "Umbrela",
  Status: "Status",
  reserve_not_paid: "Rezerva(Fara plata)",
  reserved_paid: "Rezerva(Cu plata)",
  Days_selected: "Zile selectate",
  discount_alert: "Discountul mai mare ca pretul total",
  Created_by: "Creat de",
  Go_in: "Acceseaza",
  Reservation_Number: "Numar rezervare",
  new_on_smart_beach: "Nou pe Tabo?",
  already_have_account: "Ai deja un cont?",
  SIGN_UP: "Inregistreaza-te",
  LOG_IN: "Logheaza-te",
  Receptionist: "Receptioner",
  Search_location: "Cauta locatie",
  UserName: "Nume utilizator",
  Code: "Cod",
  Verify: "Verifica",
  New_password: "Parola noua",
  Confirm_password: "Confirma parola",
  username_password_incorrect: "Nume utilizator incorect",
  password_incorrect: "Parola incorecta",
  //////////////////////////////
  Reservation_Data: "Detalii rezervare",
  Reservation_No: "Nr. Rezervare",
  Phone_No: "No. Telefon",
  Period: "Perioada",
  Price: "Pret",
  Scan_again: "Scaneaza din nou",
  Confirm_Arrival: "Confirma Sosire",
  Reservation_Not_found: "Rezervare negasita",
  Name_Phone_No: "Nume si Nr. Telefon",
  Success_change_status: "Status schimbat cu succes",
  different_select_days: "Zile diferite",
  Change_Status: "Schimba status",
  Table_Number: "Numar Masa",
  Reservation_day: "Zi rezervare",
  Arrive_time: "Ora sosire",
  number_of_persons: "Numar Persoane",
  persons: "Persoane",
  View: "Vezi",
  Change: "Schimba",
  Completed: "Terminat",
  Arrived: "Sosit",
  Remove: "Sterge",
  //////////////////////////////////////////
  INFO: "INFO",
  ConfirmationAlert1: "NU pot crea o rezervare inainte de timpul prezent",
  ConfirmationAlert2: "Reconsidera alegerea facuta",
  Confirm_changings: "Confirma Modificarile",
  from_start_hour: "De la",
  to: "pana la",
  from_table: "- De la masa",
  to_table: "la masa",
  time_occupied_from: "Timp ocupat de la",
  min: "min",
  change_status_canceled: "Schimba status: Anulat",
  are_you_sure: "Esti sigur?",
  ok: "OK",
  change_status_occupied: "Schimba status: Ocupat",
  change_status_completed: "Schimba status: Terminat",
  Phone_Number: "Nr. telefon",
  Number_of_persons: 'Nr. Persoane',
  Date: 'Data',
  Start_Time: "De la ora",
  Range: "Perioada",
  mins: "minute",
  mark_booked: "Marcheaza rezervat",
  mark_occupied: "Marcheaza ocupat",
  Late: "Intarzie",
  Failed_storage: "Datele nu au putut fi colectate din Memoria locala",
  Success_update: "Updatat cu succes",
  Success_Release: "Eliberat cu succes",
  Break_time: "Pauza",
  Colitions: "Rezervarile se suprapun, aceasta actiune nu este permisa",
  Name_must_be_exist: "Numele este obligatoriu",
  Selected_Seats: "Locuri selectate",
  Calendar: "Calendar",
  Select_Individual_Days: "Selecteaza zile diferite"
};